name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./source
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        working-directory: ${{working-directory}}
        run: dotnet restore 
      - name: Build
        working-directory: ${{working-directory}}
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: ${{working-directory}}
        run: dotnet test --no-restore --verbosity normal
